# Generated by Django 4.2.7 on 2026-01-21 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gates.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatedTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, default=gates.models._generate_public_id, editable=False, max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('soundcloud_track_url', models.URLField(help_text='Public SoundCloud URL to the track')),
                ('soundcloud_track_urn', models.CharField(blank=True, db_index=True, max_length=128)),
                ('soundcloud_artist_urn', models.CharField(blank=True, db_index=True, max_length=128)),
                ('soundcloud_artist_username', models.CharField(blank=True, max_length=255)),
                ('require_like', models.BooleanField(default=True)),
                ('require_comment', models.BooleanField(default=True)),
                ('require_follow', models.BooleanField(default=False)),
                ('download_file', models.FileField(blank=True, upload_to='gated_downloads/%Y/%m/%d/')),
                ('download_filename', models.CharField(blank=True, help_text='Optional filename to use for the downloaded file.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gated_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatedFollowTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(blank=True)),
                ('soundcloud_user_urn', models.CharField(blank=True, db_index=True, max_length=128)),
                ('soundcloud_username', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_targets', to='gates.gatedtrack')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('track', 'profile_url'), ('track', 'soundcloud_user_urn')},
            },
        ),
        migrations.CreateModel(
            name='GateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundcloud_user_urn', models.CharField(db_index=True, max_length=128)),
                ('soundcloud_username', models.CharField(blank=True, max_length=255)),
                ('verified_like', models.BooleanField(default=False)),
                ('verified_comment', models.BooleanField(default=False)),
                ('verified_follow', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_download_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_accesses', to='gates.gatedtrack')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('track', 'soundcloud_user_urn')},
            },
        ),
    ]
