# Generated by Django 4.2.7 on 2026-01-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedtrack',
            name='notify_on_downloads',
            field=models.BooleanField(default=True, help_text='Send an email notification to the gate owner when someone downloads.'),
        ),
    ]
