# Generated by Django 4.2.7 on 2026-01-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gates', '0002_follow_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatedtrack',
            name='download_file',
            field=models.FileField(blank=True, upload_to='gated_downloads/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='GatedFollowTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.URLField(blank=True)),
                ('soundcloud_user_urn', models.CharField(blank=True, db_index=True, max_length=128)),
                ('soundcloud_username', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_targets', to='gates.gatedtrack')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('track', 'soundcloud_user_urn'), ('track', 'profile_url')},
            },
        ),
    ]
