# Generated by Django 4.2.7 on 2026-01-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_on_downloads',
            field=models.BooleanField(default=True, help_text='Send me an email when someone downloads a file from one of my gates.'),
        ),
    ]
